PierresSweets/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresSweets.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    public string TreatName { get; set; }
    public List<TreatFlavor> JoinEntities { get; }
  }

}

PierresSweets/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresSweets.Models;

namespace PierresSweets.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly PierresSweetsContext _db;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresSweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      ViewBag.Treats = _db.Treats.ToList();
      Flavor thisFlavor = _db.Flavors
                            .Include(flavor => flavor.JoinEntities)
                            .ThenInclude(join => join.Treat)
                            .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if(joinEntity == null && treatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId});
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId});
    }

    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id); 
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.FlavorId});
    }

  }
}

PierresSweets/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresSweets.Models;

namespace PierresSweets.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly PierresSweetsContext _db;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresSweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      ViewBag.Flavors = _db.Flavors.ToList();
      Treat thisTreat = _db.Treats
                            .Include(treat => treat.JoinEntities)
                            .ThenInclude(join => join.Flavor)
                            .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId});
    }
  }
}

PierresSweets/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierresSweets.Models.Treat

<h1>Add Flavor to: @Html.DisplayFor(model => model.TreatName)</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  <h3>@Html.Label("Select Flavor") @Html.DropDownList("FlavorId")</h3>
  <br>

  <input type="submit" value="Add" class="btn btn-lg btn-info" style="margin-bottom: 4%;"/>
}

<p class="enlarge">@Html.ActionLink("Back to Treats", "Index")</p>

PierresSweets/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

<h1>Create Treat</h1>

@model PierresSweets.Models.Treat
@using (@Html.BeginForm())
{
  <h3>Treat: @Html.TextBoxFor(model => model.TreatName, new { placeholder="Treat Name"})</h3>
  <input type="submit" value="Create" class="btn btn-info">
}

<p class="enlarge">@Html.ActionLink("Back to Treats", "Index")</p>
<p class="enlarge">@Html.ActionLink("Main Menu", "Index", "Home")</p>

PierresSweets/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

<h1>Delete Treat</h1>
@model PierresSweets.Models.Treat

<ul>
  <li>Name: @Html.DisplayFor(model => model.TreatName)</li>
</ul>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger btn-md" style="margin-bottom: 3%">
}

<p class="enlarge">@Html.ActionLink("Back to Treats", "Index")</p>
<p class="enlarge">@Html.ActionLink("Main Menu", "Index", "Home")</p

PierresSweets/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

<h1>Treat Details</h1>
<hr>

@model PierresSweets.Models.Treat
@using PierresSweets.Models

<h2>@Html.DisplayFor(model => model.TreatName)</h2>

@if (@Model.JoinEntities.Count == 0 && @ViewBag.Flavors.Count == 0)
{
  <p class="text-danger" style="font-weight: bold;">*No flavors are available*</p>
  <p class="text-danger">Treat cannot be assiged a flavor until a flavor is added to flavor list</p>
  <p class="enlarge" style="margin-bottom: 4%;">@Html.ActionLink("Add Flavor to Flavor List", "Create", "Flavors")</p>
}
else if (@Model.JoinEntities.Count == 0)
{
  <p class="text-danger">This treat has no flavors yet..</p>
  <p class="enlarge" style="margin-bottom: 4%;">@Html.ActionLink("Add Flavor to Treat", "AddFlavor", new { id = Model.TreatId})</p>
} 
else
{
  <h3 style="margin-bottom: 2%;">Flavors:</h3>
   <ul>
    @foreach (TreatFlavor join in Model.JoinEntities)
    {
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
       <li> 
        @join.Flavor.FlavorName |
        @Html.Hidden("joinId", @join.TreatFlavorId)
        <input type="submit" value="Delete" class="btn btn-danger btn-md"/>
      </li>
      }
    }
  </ul>
<p class="enlarge" style="margin-bottom: 4%;">@Html.ActionLink("Add Flavor to Treat", "AddFlavor", new { id = Model.TreatId})</p>
}
<hr style="font-size: 10px;">

<p class="enlarge">@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId})</p>
<p class="enlarge">@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId})</p>
<p class="enlarge">@Html.ActionLink("Back to Treats", "Index")</p>
<p class="enlarge">@Html.ActionLink("Main Menu", "Index", "Home")</p>

PierresSweets/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresSweets.Models.Treat

<h1>Edit Treat Info Below</h1>
@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  <li>Name: @Html.EditorFor(model => model.TreatName, new {placeholder = @Html.DisplayFor(model => model.TreatName)})</li>
  
  <input type="submit" value="Edit" class="btn btn-lg btn-info" style="margin-top: 4%;, margin-bottom: 3%;"/>
}

<p class="enlarge">@Html.ActionLink("Back to Treats", "Index")</p>
<p class="enlarge">@Html.ActionLink("Main Menu", "Index", "Home")</p>

PierresSweets/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Treats</h1>
<hr>

@using PierresSweets.Models

@if(Model.Count == 0)
{
  <h2>No treats yet..</h2>
}
else
{
  <ul style="margin-bottom: 4%;">
  @foreach(Treat treat in Model)
  {
    <li class="enlarge">@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
  }
  </ul>
}

<p class="enlarge">@Html.ActionLink("Create Treat", "Create", "Treats")</p>
<p class="enlarge">@Html.ActionLink("Main Menu", "Index", "Home")</p>